# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get the prewhitening matrix for a single data location
#'
#' @param AR_coeffs a length-p vector where p is the AR order
#' @param nTime (integer) the length of the time series that is being prewhitened
#' @param avg_var a scalar value of the residual variances of the AR model
#' @export
getSqrtInvCpp <- function(AR_coeffs, nTime, avg_var) {
    .Call(`_BayesfMRI_getSqrtInvCpp`, AR_coeffs, nTime, avg_var)
}

